# Distributed under the MIT License.
# See LICENSE.txt for details.

add_subdirectory(add_2_oneline)
add_subdirectory(add_4_oneline)
add_subdirectory(add_8_oneline)
add_subdirectory(add_16_oneline)
add_subdirectory(add_32_oneline)
add_subdirectory(add_64_oneline)
add_subdirectory(add_128_oneline)
add_subdirectory(add_256_oneline)
add_subdirectory(add_2_plus_equals)
add_subdirectory(add_4_plus_equals)
add_subdirectory(add_8_plus_equals)
add_subdirectory(add_16_plus_equals)
add_subdirectory(add_32_plus_equals)
add_subdirectory(add_64_plus_equals)
add_subdirectory(add_128_plus_equals)
add_subdirectory(add_256_plus_equals)
add_subdirectory(prod_sum_2_oneline)
add_subdirectory(prod_sum_4_oneline)
add_subdirectory(prod_sum_8_oneline)
add_subdirectory(prod_sum_16_oneline)
add_subdirectory(prod_sum_32_oneline)
add_subdirectory(prod_sum_64_oneline)
add_subdirectory(prod_sum_128_oneline)
add_subdirectory(prod_sum_256_oneline)
add_subdirectory(prod_sum_256_unique_ops_oneline)
add_subdirectory(prod_sum_2_plus_equals)
add_subdirectory(prod_sum_4_plus_equals)
add_subdirectory(prod_sum_8_plus_equals)
add_subdirectory(prod_sum_16_plus_equals)
add_subdirectory(prod_sum_32_plus_equals)
add_subdirectory(prod_sum_64_plus_equals)
add_subdirectory(prod_sum_128_plus_equals)
add_subdirectory(prod_sum_256_plus_equals)
add_subdirectory(prod_sum_256_unique_ops_plus_equals)
add_subdirectory(inner_product_spacetime_4x4_loop)
add_subdirectory(inner_product_spacetime_4x4_oneline)
add_subdirectory(inner_product_spacetime_4x4_recursive)
add_subdirectory(inner_product_spacetime_4x4_recursive_plus_equals)
