# Distributed under the MIT License.
# See LICENSE.txt for details.

if (NOT DEFINED(SPECTRE_USE_ALWAYS_INLINE))
  if (${CMAKE_BUILD_TYPE} STREQUAL "Debug")
    set(
        _SPECTRE_USE_ALWAYS_INLINE 0
    )
  else()
    set(
        _SPECTRE_USE_ALWAYS_INLINE 1
    )
  endif()
endif()

message(STATUS "_SPECTRE_USE_ALWAYS_INLINE : ${_SPECTRE_USE_ALWAYS_INLINE}")

set_property(
  TARGET SpectreFlags
  APPEND PROPERTY
  INTERFACE_COMPILE_DEFINITIONS
  $<$<COMPILE_LANGUAGE:CXX>:SPECTRE_USE_ALWAYS_INLINE=${_SPECTRE_USE_ALWAYS_INLINE}>
)
